# Generated by Django 5.0.4 on 2024-04-19 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='admin',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='gestionnaire',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='gestionnaire',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='gestionnaire',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='vendeur',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='vendeur',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='vendeur',
            name='telephone',
        ),
        migrations.AddField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='custom_users', related_query_name='custom_user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_users_permissions', related_query_name='custom_user_permission', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='store.profile'),
            preserve_default=False,
        ),
    ]
